export const ACTION_TYPE = {
  ADDTOCART: "ADDTOCART",
  INCREMENTPRODUCT: "INCREMENTPRODUCT",
  DECREMENTPRODUCT: "DECREMENTPRODUCT",
  TOTALPRICE: "TOTALPRICE",
  TOTALITEMS: "TOTALITEMS",
  DELETEITEM: "DELETEITEM",
  DELETECART: "DELETECART",
  LOGIN: "LOGIN",
};
